name: smart_appbar
description: A powerful and intelligent SmartAppBar widget for Flutter that automatically adapts to routes, supports multiple visual variants, and provides seamless Material 3 design experience.
version: 1.0.4
repository: https://github.com/manar42/SmartAppBar-


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

topics:
  - appbar
  - smart
  - adaptive
  - material3
  - ui
  - widget
  - flutter
  - flutter-package